name: Setup Script

on: pull_request_target

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        run: chmod +x script.sh && ./script.sh
      
